language: shell
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add clair-scanner ./
  - asdf list-all clair-scanner
  - asdf plugin-test clair-scanner ./ 'clair-scanner --help'
os:
  - osx
  - linux
